"""Acceptance length vs. draft budget up to m=22, averaged over the four
workloads: chain, (6,2) tree, (6,4) tree, one panel per model.

    python3 tree_budget_ext.py          # preview
    python3 tree_budget_ext.py --save   # write pdf + png next to this file

The numbers live in the DATA block below, one line per series and one column
per budget in M (None = not run). GLM rows are SGLang measurements. Nemotron
rows are SGLang measurements where the *_SRC row says 'M' and estimates
elsewhere ('J' July split-stack value + engine offset, 'Q' the 100-request
point mapped to the full set, 'E' interpolated along GLM's curve); the block
is (re)generated by tree_budget_ext_estimate.py --write and can be edited by
hand. With MARK_ESTIMATES, non-'M' Nemotron points are drawn hollow.
"""
import argparse
from pathlib import Path

HERE = Path(__file__).resolve().parent
DATA = HERE / "data"

FIG_W = 3.335
PANEL_H = 0.40             # plot area per model, inches (0.523 before the page cut)
FONT_TICK, FONT_LABEL = 8.0, 9.0
FONT_SERIF = ["STIXGeneral", "DejaVu Serif"]

SERIES = [  # (key, label, color, marker, linestyle)
    ("chain", "Chain", "#555555", "o", (0, (3, 2))),
    ("n6k2", "Tree (6,2)", "#184F95", "s", "-"),
    ("n6k4", "Tree (6,4)", "#C8511B", "^", "-"),
]
MARK_ESTIMATES = False  # hollow markers for Nemotron points not measured on SGLang (none left)

# ####################################################################
# DATA  (mean tau over the four workloads; columns follow M)
# ####################################################################
# BEGIN DATA
# GLM-4.5-Air: measured on SGLang (the acceptance sweep of Section 3.2).
M              = [    3,     4,     5,     6,     7,     8,     9,    10,    12,    14,    16,    18,    20,    22]
GLM_CHAIN     = [ 2.89,  3.07,  3.15,  3.18,  3.20,  3.19,  3.22,  3.18,  3.20,  None,  3.21,  None,  None,  3.21]
GLM_TREE62    = [ 2.95,  3.19,  3.35,  3.48,  3.58,  3.62,  3.67,  3.72,  3.78,  3.82,  3.82,  3.84,  3.85,  3.87]
GLM_TREE64    = [ 2.95,  3.20,  3.39,  3.51,  3.61,  3.70,  3.76,  3.81,  3.93,  4.02,  4.05,  4.11,  4.15,  4.19]
# Nemotron-3-Super: measured on SGLang (results/nemotron_sglang_fig6_2026-09-14),
# all 39 grid points. The SRC rows record provenance: M = measured on SGLang;
# J/Q/E marked the interim estimates that tree_budget_ext_estimate.py filled in
# before the grid finished (none remain), '-' = budget not in the chain grid.
NEM_CHAIN     = [ 3.14,  3.45,  3.65,  3.72,  3.74,  3.78,  3.76,  3.77,  3.77,  None,  3.78,  None,  None,  3.76]
NEM_TREE62    = [ 3.16,  3.54,  3.82,  4.00,  4.13,  4.24,  4.29,  4.36,  4.44,  4.49,  4.50,  4.51,  4.53,  4.56]
NEM_TREE64    = [ 3.17,  3.55,  3.85,  4.01,  4.14,  4.27,  4.36,  4.44,  4.56,  4.65,  4.72,  4.81,  4.85,  4.91]
NEM_CHAIN_SRC = [  'M',   'M',   'M',   'M',   'M',   'M',   'M',   'M',   'M',   '-',   'M',   '-',   '-',   'M']
NEM_TREE62_SRC= [  'M',   'M',   'M',   'M',   'M',   'M',   'M',   'M',   'M',   'M',   'M',   'M',   'M',   'M']
NEM_TREE64_SRC= [  'M',   'M',   'M',   'M',   'M',   'M',   'M',   'M',   'M',   'M',   'M',   'M',   'M',   'M']
# END DATA
# ####################################################################


def series_points():
    """{model: {key: {m: (tau, measured)}}} from the DATA block."""
    out = {}
    for model, rows in (("Nemotron-3-Super", (NEM_CHAIN, NEM_TREE62, NEM_TREE64)),
                        ("GLM-4.5-Air", (GLM_CHAIN, GLM_TREE62, GLM_TREE64))):
        srcs = (NEM_CHAIN_SRC, NEM_TREE62_SRC, NEM_TREE64_SRC) if model.startswith("Nemotron") else (None,) * 3
        out[model] = {}
        for (key, *_), row, src in zip(SERIES, rows, srcs):
            assert len(row) == len(M), f"{model} {key}: {len(row)} values for {len(M)} budgets"
            out[model][key] = {m: (v, src is None or src[i] == "M")
                               for i, (m, v) in enumerate(zip(M, row)) if v is not None}
    return out


def build_figure():
    import matplotlib.pyplot as plt
    plt.rcParams.update({"font.family": "serif", "font.serif": FONT_SERIF,
                         "mathtext.fontset": "stix", "pdf.fonttype": 42, "ps.fonttype": 42,
                         "axes.linewidth": 0.6, "xtick.labelsize": FONT_TICK,
                         "ytick.labelsize": FONT_TICK})
    models = list(series_points().items())
    fig, axes = plt.subplots(2, 1, figsize=(FIG_W, 2 * PANEL_H + 0.50), sharex=True,
                             layout="constrained")
    fig.get_layout_engine().set(w_pad=0.01, h_pad=0.005, hspace=0.06)
    handles = []
    for ax, (name, pts) in zip(axes, models):
        for key, label, color, marker, ls in SERIES:
            ms = sorted(pts[key])
            if not ms:
                continue
            h, = ax.plot(ms, [pts[key][m][0] for m in ms], color=color, marker=marker,
                         ms=3.2, lw=1.0, ls=ls, label=label, markeredgewidth=0.6,
                         markerfacecolor="white" if key == "chain" else color)
            if ax is axes[1]:
                handles.append(h)
            if MARK_ESTIMATES:
                est = [m for m in ms if not pts[key][m][1]]
                if est:
                    ax.plot(est, [pts[key][m][0] for m in est], color=color, marker=marker,
                            ms=3.4, lw=0, markeredgewidth=0.7, markerfacecolor="white")
        ax.text(0.015, 0.93, name, transform=ax.transAxes, ha="left", va="top",
                fontsize=FONT_TICK, color="#222222")
        ax.grid(True, lw=0.4, color="#DDDDDD"); ax.set_axisbelow(True)
        ax.tick_params(length=2.5, width=0.5, pad=1.5)
        for sp in ("top", "right"):
            ax.spines[sp].set_visible(False)
    axes[1].set_xticks([3, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22])
    axes[1].set_xlabel("Draft budget $m$", fontsize=FONT_LABEL, labelpad=0)
    # One line: the caption says the curves average the four workloads.
    fig.supylabel("Acceptance length $\\tau$", fontsize=FONT_LABEL)
    axes[0].legend(handles=handles, loc="lower center", bbox_to_anchor=(0.5, 1.0), ncol=3,
                   fontsize=FONT_TICK, frameon=False, handlelength=2.2, columnspacing=1.2,
                   borderaxespad=0.05, borderpad=0.0)
    return fig


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--save", action="store_true")
    args = ap.parse_args()
    if args.save:
        import matplotlib; matplotlib.use("Agg")
        fig = build_figure()
        out = HERE / "tree_budget_ext.pdf"
        fig.savefig(out); fig.savefig(out.with_suffix(".png"), dpi=300); print("wrote", out)
    else:
        import matplotlib.pyplot as plt
        build_figure(); plt.show()


if __name__ == "__main__":
    main()
